MODEL:
  TYPE: vssm
  NAME: msvmambav3_small_224
  DROP_PATH_RATE: 0.4
  VSSM:
    EMBED_DIM: 96
    DEPTHS: [ 2, 3, 20, 2]
    SSM_D_STATE: 1
    SSM_DT_RANK: "auto"
    SSM_RATIO: 1.0
    SSM_FORWARDTYPE: "vms_noz" # v3_noz
    DOWNSAMPLE: "v3"
    PATCHEMBED: "v2"
    NORM_LAYER: "ln2d"
    CONVFFN: True
    ADD_SE: True
    CONV_FFN_RATIO: 4

  DDP: 'torch'
